global:
  scrape_interval: 15s

scrape_configs:
  - job_name: control-plane
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: worker
    static_configs:
      - targets: ["host.docker.internal:8081"]
